version: "3.8"

services:
  hitomi:
    image: selachon/hitomi:latest
    build: .
    container_name: hitomi
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      NODE_OPTIONS: --dns-result-order=ipv4first
    dns:
      - 1.1.1.1
      - 8.8.8.8
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
